repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0 # C++ 社区常用的通用 commit 约束版本
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
